// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: LILYGO-T-Display-S3-RSSI_Monitor

#ifndef _LILYGO_T_DISPLAY_S3_RSSI_MONITOR_UI_H
#define _LILYGO_T_DISPLAY_S3_RSSI_MONITOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_wifiPNGPanel;
extern lv_obj_t * ui_devNameLabel;
extern lv_obj_t * ui_WiFiTestLabel;
extern lv_obj_t * ui_RSSILabel;
extern lv_obj_t * ui_RSSItextLabel;
extern lv_obj_t * ui_HLine1;
extern lv_obj_t * ui_RSSIBar;
extern lv_obj_t * ui_RSSILevelsLabel;
extern lv_obj_t * ui_RSSIval;
extern lv_obj_t * ui_dbmValuesLabel;
extern lv_obj_t * ui_RSSIave;
extern lv_obj_t * ui_RSSImax;
extern lv_obj_t * ui_RSSImin;
extern lv_obj_t * ui_dBmLabel;
extern lv_obj_t * ui_FPSLabel;
extern lv_obj_t * ui_FPS;
extern lv_obj_t * ui_VLine;
extern lv_obj_t * ui_statusLabel;
extern lv_obj_t * ui_PingLabel;
extern lv_obj_t * ui_PingTime;
extern lv_obj_t * ui_connected;
extern lv_obj_t * ui_disconnected;
extern lv_obj_t * ui_HLine2;
extern lv_obj_t * ui_MACLabel;
extern lv_obj_t * ui_MACadd;
extern lv_obj_t * ui_IPLabel;
extern lv_obj_t * ui_IPadd;
extern lv_obj_t * ui_GWLabel;
extern lv_obj_t * ui_GWadd;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1611841627);    // assets/speedometer-64px.png

// FONTS
LV_FONT_DECLARE(ui_font_KenyanCoffeeRg12);
LV_FONT_DECLARE(ui_font_KenyanCoffeeRg15);
LV_FONT_DECLARE(ui_font_KenyanCoffeeRg17);
LV_FONT_DECLARE(ui_font_KenyanCoffeeRg20);
LV_FONT_DECLARE(ui_font_KenyanCoffeeRg30);
LV_FONT_DECLARE(ui_font_KenyanCoffeeRg40);
LV_FONT_DECLARE(ui_font_KenyanCoffeeRg50);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
