// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: LILYGO-T-Display-S3-RSSI_Monitor

#include "ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_MainScreen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x030F16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiPNGPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_wifiPNGPanel, 64);
    lv_obj_set_height(ui_wifiPNGPanel, 48);
    lv_obj_set_x(ui_wifiPNGPanel, -127);
    lv_obj_set_y(ui_wifiPNGPanel, -60);
    lv_obj_set_align(ui_wifiPNGPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wifiPNGPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_wifiPNGPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifiPNGPanel, lv_color_hex(0x030F16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiPNGPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_wifiPNGPanel, &ui_img_1611841627, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_wifiPNGPanel, lv_color_hex(0x886C0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_wifiPNGPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifiPNGPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_devNameLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_devNameLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_devNameLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_devNameLabel, -58);
    lv_obj_set_y(ui_devNameLabel, -77);
    lv_obj_set_align(ui_devNameLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_devNameLabel, "LILYGO T-DISPLAY-S3");
    lv_obj_clear_flag(ui_devNameLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_devNameLabel, lv_color_hex(0xA0BAD3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_devNameLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_devNameLabel, &ui_font_KenyanCoffeeRg12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiTestLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_WiFiTestLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiTestLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiTestLabel, -38);
    lv_obj_set_y(ui_WiFiTestLabel, -52);
    lv_obj_set_align(ui_WiFiTestLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiTestLabel, "WiFi TEST");
    lv_obj_clear_flag(ui_WiFiTestLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_WiFiTestLabel, lv_color_hex(0xA0BAD3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WiFiTestLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WiFiTestLabel, &ui_font_KenyanCoffeeRg40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RSSILabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_RSSILabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RSSILabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RSSILabel, -132);
    lv_obj_set_y(ui_RSSILabel, -17);
    lv_obj_set_align(ui_RSSILabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RSSILabel, "RSSI");
    lv_obj_clear_flag(ui_RSSILabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_RSSILabel, lv_color_hex(0x4C6B8A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RSSILabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RSSILabel, &ui_font_KenyanCoffeeRg40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RSSItextLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_RSSItextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RSSItextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RSSItextLabel, -62);
    lv_obj_set_y(ui_RSSItextLabel, -17);
    lv_obj_set_align(ui_RSSItextLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RSSItextLabel, "Received Signal \nStrength Indicator");
    lv_obj_clear_flag(ui_RSSItextLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_RSSItextLabel, lv_color_hex(0x484D30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RSSItextLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RSSItextLabel, &ui_font_KenyanCoffeeRg15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HLine1 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_HLine1, 140);
    lv_obj_set_height(ui_HLine1, 2);
    lv_obj_set_x(ui_HLine1, -89);
    lv_obj_set_y(ui_HLine1, 8);
    lv_obj_set_align(ui_HLine1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HLine1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_HLine1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_HLine1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HLine1, lv_color_hex(0x8095BC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HLine1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HLine1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RSSIBar = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_RSSIBar, 4);
    lv_obj_set_height(ui_RSSIBar, 15);
    lv_obj_set_x(ui_RSSIBar, -13);
    lv_obj_set_y(ui_RSSIBar, -22);
    lv_obj_set_align(ui_RSSIBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RSSIBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_RSSIBar, lv_color_hex(0xD52020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RSSIBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RSSIBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_RSSIBar, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_RSSILevelsLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_RSSILevelsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RSSILevelsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RSSILevelsLabel, 4);
    lv_obj_set_y(ui_RSSILevelsLabel, 24);
    lv_obj_set_align(ui_RSSILevelsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RSSILevelsLabel, "BEST\nGOOD\nFAIR\nWEEK\nPOOR\nBAD");
    lv_obj_clear_flag(ui_RSSILevelsLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_RSSILevelsLabel, lv_color_hex(0x68819A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RSSILevelsLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RSSILevelsLabel, &ui_font_KenyanCoffeeRg17, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RSSIval = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_RSSIval, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RSSIval, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RSSIval, 2);
    lv_obj_set_y(ui_RSSIval, 95);
    lv_label_set_text(ui_RSSIval, "-00");
    lv_obj_clear_flag(ui_RSSIval, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_RSSIval, lv_color_hex(0xB5CADF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RSSIval, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RSSIval, &ui_font_KenyanCoffeeRg50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dbmValuesLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_dbmValuesLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dbmValuesLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dbmValuesLabel, -71);
    lv_obj_set_y(ui_dbmValuesLabel, 37);
    lv_obj_set_align(ui_dbmValuesLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dbmValuesLabel, "AVE:\nMAX:\nMIN:");
    lv_obj_clear_flag(ui_dbmValuesLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_dbmValuesLabel, lv_color_hex(0x43566A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dbmValuesLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dbmValuesLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RSSIave = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_RSSIave, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RSSIave, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RSSIave, 107);
    lv_obj_set_y(ui_RSSIave, 101);
    lv_label_set_text(ui_RSSIave, "-00 dBm");
    lv_obj_clear_flag(ui_RSSIave, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_RSSIave, lv_color_hex(0xB5CADF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RSSIave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RSSIave, &ui_font_KenyanCoffeeRg12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RSSImax = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_RSSImax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RSSImax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RSSImax, 107);
    lv_obj_set_y(ui_RSSImax, 116);
    lv_label_set_text(ui_RSSImax, "-00 dBm");
    lv_obj_clear_flag(ui_RSSImax, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_RSSImax, lv_color_hex(0xB5CADF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RSSImax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RSSImax, &ui_font_KenyanCoffeeRg12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RSSImin = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_RSSImin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RSSImin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RSSImin, 107);
    lv_obj_set_y(ui_RSSImin, 131);
    lv_label_set_text(ui_RSSImin, "-00 dBm");
    lv_obj_clear_flag(ui_RSSImin, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_RSSImin, lv_color_hex(0xB5CADF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RSSImin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RSSImin, &ui_font_KenyanCoffeeRg12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dBmLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_dBmLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dBmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dBmLabel, -75);
    lv_obj_set_y(ui_dBmLabel, 69);
    lv_obj_set_align(ui_dBmLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dBmLabel, "dBm");
    lv_obj_clear_flag(ui_dBmLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_dBmLabel, lv_color_hex(0x526880), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dBmLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dBmLabel, &ui_font_KenyanCoffeeRg17, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FPSLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_FPSLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FPSLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FPSLabel, -44);
    lv_obj_set_y(ui_FPSLabel, 70);
    lv_obj_set_align(ui_FPSLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FPSLabel, "FPS :");
    lv_label_set_recolor(ui_FPSLabel, "true");
    lv_obj_clear_flag(ui_FPSLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_FPSLabel, lv_color_hex(0x305274), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FPSLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FPSLabel, &ui_font_KenyanCoffeeRg15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FPS = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_FPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FPS, -25);
    lv_obj_set_y(ui_FPS, 70);
    lv_obj_set_align(ui_FPS, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FPS, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_FPS, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_FPS, "00");
    lv_obj_clear_flag(ui_FPS, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_FPS, lv_color_hex(0x92A8C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FPS, &ui_font_KenyanCoffeeRg15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VLine = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_VLine, 2);
    lv_obj_set_height(ui_VLine, 167);
    lv_obj_set_x(ui_VLine, 23);
    lv_obj_set_y(ui_VLine, 0);
    lv_obj_set_align(ui_VLine, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VLine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VLine, lv_color_hex(0x8095BC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VLine, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_statusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_statusLabel, 45);
    lv_obj_set_y(ui_statusLabel, -76);
    lv_obj_set_align(ui_statusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_statusLabel, "STATUS:");
    lv_obj_clear_flag(ui_statusLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_statusLabel, lv_color_hex(0x856A08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_statusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_statusLabel, &ui_font_KenyanCoffeeRg15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PingLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_PingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PingLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PingLabel, 111);
    lv_obj_set_y(ui_PingLabel, -78);
    lv_obj_set_align(ui_PingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PingLabel, "PING :");
    lv_label_set_recolor(ui_PingLabel, "true");
    lv_obj_clear_flag(ui_PingLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_PingLabel, lv_color_hex(0x305274), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PingLabel, &ui_font_KenyanCoffeeRg12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PingTime = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_PingTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PingTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PingTime, -3);
    lv_obj_set_y(ui_PingTime, -78);
    lv_obj_set_align(ui_PingTime, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_PingTime, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PingTime, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PingTime, "0000 ms");
    lv_obj_clear_flag(ui_PingTime, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_PingTime, lv_color_hex(0x92A8C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PingTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PingTime, &ui_font_KenyanCoffeeRg12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connected = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_connected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connected, 189);
    lv_obj_set_y(ui_connected, 14);
    lv_label_set_text(ui_connected, "CONENCTED	");
    lv_obj_clear_flag(ui_connected, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_connected, lv_color_hex(0x13511E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connected, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connected, &ui_font_KenyanCoffeeRg30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_disconnected = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_disconnected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_disconnected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_disconnected, 187);
    lv_obj_set_y(ui_disconnected, 14);
    lv_label_set_text(ui_disconnected, "DISCONNECTED");
    lv_obj_add_flag(ui_disconnected, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_disconnected, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_disconnected, lv_color_hex(0x511313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_disconnected, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_disconnected, &ui_font_KenyanCoffeeRg30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HLine2 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_HLine2, 130);
    lv_obj_set_height(ui_HLine2, 2);
    lv_obj_set_x(ui_HLine2, 92);
    lv_obj_set_y(ui_HLine2, -37);
    lv_obj_set_align(ui_HLine2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HLine2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_HLine2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_HLine2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HLine2, lv_color_hex(0x8095BC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HLine2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HLine2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MACLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_MACLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MACLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MACLabel, 69);
    lv_obj_set_y(ui_MACLabel, -22);
    lv_obj_set_align(ui_MACLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MACLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_MACLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_MACLabel, "MAC Address:");
    lv_label_set_recolor(ui_MACLabel, "true");
    lv_obj_clear_flag(ui_MACLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MACLabel, lv_color_hex(0x305274), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MACLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MACLabel, &ui_font_KenyanCoffeeRg20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MACadd = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_MACadd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MACadd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MACadd, 190);
    lv_obj_set_y(ui_MACadd, -4);
    lv_obj_set_align(ui_MACadd, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_MACadd, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_MACadd, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_MACadd, "FF:FF:FF:FF:FF:FF");
    lv_obj_clear_flag(ui_MACadd, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_MACadd, lv_color_hex(0x92A8C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MACadd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MACadd, &ui_font_KenyanCoffeeRg20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_IPLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPLabel, 61);
    lv_obj_set_y(ui_IPLabel, 15);
    lv_obj_set_align(ui_IPLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_IPLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_IPLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_IPLabel, "IP Address:");
    lv_label_set_recolor(ui_IPLabel, "true");
    lv_obj_clear_flag(ui_IPLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_IPLabel, lv_color_hex(0x305274), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPLabel, &ui_font_KenyanCoffeeRg20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPadd = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_IPadd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPadd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPadd, 190);
    lv_obj_set_y(ui_IPadd, 107);
    lv_obj_set_flex_flow(ui_IPadd, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_IPadd, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_IPadd, "192.168.254.254/24");
    lv_obj_clear_flag(ui_IPadd, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_IPadd, lv_color_hex(0x92A8C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPadd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPadd, &ui_font_KenyanCoffeeRg20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GWLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_GWLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GWLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GWLabel, 56);
    lv_obj_set_y(ui_GWLabel, 52);
    lv_obj_set_align(ui_GWLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GWLabel, "GATEWAY:");
    lv_label_set_recolor(ui_GWLabel, "true");
    lv_obj_clear_flag(ui_GWLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_GWLabel, lv_color_hex(0x305274), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GWLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GWLabel, &ui_font_KenyanCoffeeRg20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GWadd = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_GWadd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GWadd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GWadd, 190);
    lv_obj_set_y(ui_GWadd, 144);
    lv_label_set_text(ui_GWadd, "192.168.254.254");
    lv_obj_clear_flag(ui_GWadd, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_GWadd, lv_color_hex(0x92A8C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GWadd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GWadd, &ui_font_KenyanCoffeeRg20, LV_PART_MAIN | LV_STATE_DEFAULT);

}
